# Generated by Django 3.1.7 on 2021-08-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartrate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hr',
            old_name='username',
            new_name='user',
        ),
    ]
